### PR TITLE
React Native CallKeep upstream + fixes

### PR DESCRIPTION
**Pull request by tombaranowicz**
Our current prod builds are already based on this upstreamed branch, so I believe it's worth merging it and switching the mobile app to once again use the master of our fork.

### CODE REVIEW

**Review by Kelt — APPROVED** [review]
Looking good, we will have enough time to test this in stage before next normal release :+1:

**Review by tzahola — APPROVED** [review]

**Comment by gerhardberger** [comment]
@tombaranowicz does that mean that we released PROD mobileapp, with a branch referenced that wasn't master?

**Comment by tombaranowicz** [comment]
> 

Yes, this branch was created when I started working on CallKit on iOS, so I did not merge it to the master to make sure nothing is broken. Actually, I forgot about it when we finally merged the CallKit branch in the Around app and now just found that I have still opened the draft.

**Comment by gerhardberger** [comment]
This means that the changes on this branch didn't go through PR review and approval before hitting PROD or STAGE, which should not happen. So, next time please make sure that every dependency we use in a PROD build is merged to master in its own repo.

**Pull request merged**
